language: cpp
compiler: g++
dist: trusty
sudo: required

before_install:
  - sudo apt-get update

install:
  - sudo apt-get install libfltk1.3-dev cmake libxinerama-dev
  
script:
  - make -f Makefile.unix
  - mkdir build
  - cd build
  - cmake ..
  - make
